name: Frontend CI

on:
  push:
    branches:
      - main
      - frontend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: build
        run: npm ci
        working-directory: Frontend
      - name: test
        run: npm run test
        working-directory: Frontend

  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: build
        run: npm ci
        working-directory: Frontend
      - name: lint
        run: npm run lint
        working-directory: Frontend
